### ISSUE TITLE
Can we add "Contact us" in the menu at the top somewhere?

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#104]
to email address: contact@handsupfoundation.org

**Comment by samuelcolvin** [comment]
With a mailto link or a contact page?

I would say mailto links confused a lot of people.

**Comment by roselukas** [comment]
I was thinking mailto – interesting you think it complicates, and perhaps we do need a “contact us” page anyway. One for Cris. Will have a think about this.

R

**Comment by roselukas** [comment]
Add to custom menu slots alongside FAQs

**Comment by samuelcolvin** [comment]
replaced by #120
