### ISSUE TITLE
When booking reservation expires in 4 mins...

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#106]
... can we up this to 10? Gives people a chance to get pals in etc...? 

Can we also add a friendly message if it does expire, as opposed to Error - invalid token? If possible something like: "Oops you ran out of time, please go back to the booking page, and make sure you complete your transaction within 10 minutes. If you're stuck please contact us [contact@handsupfoundation.org]"

**Comment by samuelcolvin** [comment]
increase to 10 and fix the "invalid token"
