### ISSUE TITLE
Cover costs top up

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#107]
Think we need to make the change in amount more obvious, so that it doesn't appear sneaky. 

Can we animate the change in some way, by adding it as an amount below the check box? 
<img width="823" alt="screen shot 2018-09-05 at 14 47 56" src="https://user-images.githubusercontent.com/41365539/45097399-b47a9a80-b11a-11e8-8aac-baefc708485e.png">

**Comment by samuelcolvin** [comment]
closing for now, we can come back to this if it becomes a problem.
