### ISSUE TITLE
Just edited some text in bold in the Category long description for both categories...

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#112]
.... and it comes out not as bold but _*text text text*_

<img width="1162" alt="screen shot 2018-09-05 at 15 43 46" src="https://user-images.githubusercontent.com/41365539/45101067-9add5100-b122-11e8-9c11-8792d55e32c8.png">

**Comment by samuelcolvin** [comment]
I'm being dumb, not entirely clear what the problem is.

**Comment by roselukas** [comment]
So I just wanted the text to appear in bold - but instead it comes out in italics, with a star either side...  

_*For information on where the monies go, please click here. *_

instead of 

***For information on where the monies go, please click here. ***

**Comment by roselukas** [comment]
Ah - it appears bold doesn't appear on Github! lol.

**Comment by samuelcolvin** [comment]
markdown being weird, should be fixable.

**Comment by samuelcolvin** [comment]
This is a subtle bug in the way editor creates markdown.

If you have it again switch to the raw more and make sure bold chunks (eg. with `**` around them) don't have any spaces at the edges.

Eg.

    **this is some bold text**

but

    **this won't be bold do to an extra space at the end **

**Comment by roselukas** [comment]
Thanks!
