### ISSUE TITLE
Post purchase screen needs to be more prominent

### ISSUE THREAD

**Issue by azadiproductle** [samuelcolvin/nosht#114]
<img width="1315" alt="screen shot 2018-09-06 at 06 50 03" src="https://user-images.githubusercontent.com/41363663/45137564-27c6ef80-b1a1-11e8-8ef0-ac8c4ae4b5b4.png">

After purchase, the post-purchase screen is lost. Looks like it part of the event text (which has already been digested). 
Ideas (Rose input needed of course):

- When the blue purchase confirmation text appears, change text to say "Thank you! We've got some more to tell you about the event"
-Move the whole events block down and bring the thank you block into its own coloured (orange?) background block above.

**Comment by samuelcolvin** [comment]
add extra field to category to be displayed "Booking successful...".

**Comment by samuelcolvin** [comment]
remove short description of the event.

**Comment by samuelcolvin** [comment]
change text to "Make a donation to Hands Up Foundation" and smaller.
