### ISSUE TITLE
Chrome view scrolling issue

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#130]
When I book a ticket or edit a category in Chrome from MAC, and the category box or ticket box that comes up is longer than the bottom of my screen (so i can't see save button) if I scroll down with the bar on the right hand side, the Cateogry window then disappears and doesn't save...

Thought it was just my browser - Amira and Marina are having the same problem, not on a mac but still on chrome. 

If I use arrow keys or zoom out it is fine... weird - but I think will put some people off.

**Comment by samuelcolvin** [comment]
I@m a bit confused about what you mean, could you add a screenshot?

**Comment by samuelcolvin** [comment]
cancel all that, turns out it's already been fixed in the upstream package reactstrap/reactstrap#1097.

Fixed by simply upgrading.

**Comment by roselukas** [comment]
In which case it is what it is and we leave it. Bring on the two finger scroll….

**Comment by roselukas** [comment]
Fabulous!
