### ISSUE TITLE
IE create account issue

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#132]
Error Message comes up when I try to create an account on Internet Explorer. No problem on Google Chrome.

**Comment by samuelcolvin** [comment]
What error message? Which version of IE?

Could it be [this](https://sentry.io/the-hands-up-foundation/hands-up-events/issues/702077527/?query=is:unresolved) error?

**Comment by roselukas** [comment]
The error message is:
“Error
Invalid Recapture Value”

Version of IE is:
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

**Comment by samuelcolvin** [comment]
Yes, google has decided it's not sure whether you're a real user. Probably because you're not signed into chrome. Not much I can do about this.
