### ISSUE TITLE
Can't select a mix of tickets

### ISSUE THREAD

**Issue by azadiproductle** [samuelcolvin/nosht#140]
Tried to book kids and adults to concert. But system allows only one type of ticket to be booked at a time. 
@roselukas are you ok with this?  We discussed that users can book multiple times for different types, but for adult+ child it doesn't feel right. 
![image](https://user-images.githubusercontent.com/41363663/46631191-9e5b6200-cb3e-11e8-94cf-b57906b34cd8.png)

**Comment by roselukas** [comment]
Hi Azadi

That’s weird… and potentially a problem. Something we can resolve Samuel?

R

**Comment by samuelcolvin** [comment]
After "Select which type of ticket you wish to purchase." add an explanation about only being able to buy one ticket type.

**Comment by roselukas** [comment]
Select which type of ticket you wish to purchase. Please note that you can only buy one ticket type at a time. If you wish to buy different ticket types, return to "book now' after your initial ticket is booked.
