### ISSUE TITLE
Sign up and having First Name and Second Name

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#141]
New user buying tickets doesn’t have to signup (which is great!) – they can just get tickets. BUT when you click “Book Now” on an event, it comes up with Signup box… asking for your email. Once the email is inserted, you can then go through to book tickets, this is a bit confusing because it isn’t clear whether they have signed up or not. 

Obviously we need the email address in order to confirm ticket booking - but can we also force them to put their full name in here even if not signing up with a password?

<img width="800" alt="screen shot 2018-10-09 at 14 22 28" src="https://user-images.githubusercontent.com/41365539/46666219-ca262880-cbce-11e8-83d8-c32975571c3c.png">

**Comment by samuelcolvin** [comment]
make it like the signup page, eg. ask for name here as well as email.

**Comment by samuelcolvin** [comment]
also fixes #76
