### ISSUE TITLE
Ticket confirmation message

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#142]
I can't make the text around (Dietary requirements/access requirements) only appear if they haven't filled it in. 

Can we make this happen?

**Comment by roselukas** [comment]
Also - it currently comes through with the below... can we remove the "no thanks"? 
<img width="685" alt="screen shot 2018-10-05 at 16 53 40" src="https://user-images.githubusercontent.com/41365539/46665736-60f1e580-cbcd-11e8-90ca-f9b114b5f316.png">

**Comment by roselukas** [comment]
Rose to update category with vaguer text : 

Extra information you provided:

**Comment by samuelcolvin** [comment]
me to strip spaces.
