### ISSUE TITLE
Don't hate me - Font

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#145]
I really think the heavy Merriweather font is too much - I know it is in line with website which is what we asked for. But it makes the events quite hard to read. 

Is it at all possible to add a bit more space in here, and just use Source Sans Pro throughout? 
<img width="1075" alt="screen shot 2018-10-09 at 14 26 33" src="https://user-images.githubusercontent.com/41365539/46666419-58021380-cbcf-11e8-9ccf-8de5819efd91.png">

**Comment by samuelcolvin** [comment]
![screenshot from 2018-10-09 12-55-49](https://user-images.githubusercontent.com/4039449/46667809-af4db700-cbc2-11e8-9915-4a30fcabb249.png)

**Comment by samuelcolvin** [comment]
headings (h2 and others) to have bigger top padding.
