### ISSUE TITLE
Test site - can't find location address

### ISSUE THREAD

**Issue by azadiproductle** [samuelcolvin/nosht#154]
I typed the correct address for the V&A museum, typed search, and got a red box. Am I doing something wrong? Am in events.scolvin

![image](https://user-images.githubusercontent.com/41363663/46970798-1c28eb80-d0b2-11e8-9ef3-f982f7259958.png)

**Comment by azadiproductle** [comment]
Nothing seems to work for me, even tho it used to so I guess integration turned off? 
These don't work:
WeWork, 14 Grays Inn Rd, London WC1X 8HN
14 Grays Inn Rd, London WC1X 8HN

**Comment by samuelcolvin** [comment]
This is because the google maps API key on `events.scolvin.com` isn't working for geocoding.

In future, it'd be helpful if you could check the developer console before reporting problems like this. In this case it was fairly clear:

    Geocoding Service: This IP, site or mobile application is not authorized to use this API key....
