### ISSUE TITLE
Can't test donation adding through API

### ISSUE THREAD

**Issue by azadiproductle** [samuelcolvin/nosht#156]
a) No "post ticket" donation options screen
b) blocked by API issues on Donorfy side

**Comment by samuelcolvin** [comment]
you'll need to create these options.

Log for the demo account is the same as it's always been `frank@example.com` & `testing`

**Comment by azadiproductle** [comment]
@roselukas can you or Marina please create this in events.scolvin.com ? As you've done it before will be quicker than me figuring it out. I can then test it and test it working with the API. Thanks

**Comment by roselukas** [comment]
Sure Azadi. I’ll be back at my laptop in 30

Sent while on the run, please excuse any typos
________________________________

**Comment by samuelcolvin** [comment]
It couldn't really be simpler to create these options.

I've just created one for each of the categories.

![image](https://user-images.githubusercontent.com/4039449/47033783-98ccd000-d16d-11e8-9960-2ce0a85e0086.png)
