### ISSUE TITLE
API testing - guest transaction

### ISSUE THREAD

**Issue by azadiproductle** [samuelcolvin/nosht#157]
Add £1 transaction as guest.

A transaction is added AND a connected transaction is added: https://app.donorfy.com/Constituent/Index?Id=e5102fbb-383e-6f05-b282-ff00004460b4&EntityType=Transaction 

Any idea what this Connected Transaction is?

**Comment by samuelcolvin** [comment]
That's just what donorfy does when you create a transaction. It's very hard to read, but it is what it is.

**Comment by azadiproductle** [comment]
Sad, but as nothing we can do, won’t stress. It doesn’t impact reporting thankfully.
