### ISSUE TITLE
API testing  - guest acknowledgement text

### ISSUE THREAD

**Issue by azadiproductle** [samuelcolvin/nosht#159]
Should not be string. Should be Ticket ID. I.e. for my "Azadi TestGuest1" guest booking today the Ticket ID below should be in the Acknowledgement text field. (If you can include the text "Ticket ID: " then great. If not, no worries. )

Ticket ID: zys9i03-2

**Comment by samuelcolvin** [comment]
But there's no one-to-one link between a ticket and a transaction.

Eg. there will be one transaction if you buy 15 tickets. 

I will set `AcknowledgementText` to the ticket id of the first ticket. Hope that's ok?

**Comment by azadiproductle** [comment]
That works great. thanks

direct: +44 20 3286 6595 | mobile: +44 7837 566 595 | mail: azadi@productle.com<mailto:azadi@productle.com>
Productle Ltd, 3rd Floor, Buckingham House, Buckingham Street Aylesbury, HP20 2LA
