### ISSUE TITLE
items that need to be created in donorfy

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/nosht#164]
AFAIK, this is what needs to be created in donorfy before you can enable donorfy in production.

@azadiproductle please confirm.

Tags:

    'Hosting and helper volunteers': 'singing-for-syrians-2018-host'
    'Hosting and helper volunteers': 'syrian-supper-club-host'

ActivityTypes:

    'Event Hosted'
    'Event Booked'

Products:

    'Event Ticket(s)'
    'Donation'

Funds:

    'Unrestricted General'

Departments:

    '200 Fund Raising Income'

BankAccounts:

    'Main Account'

PaymentMethods:

    'Payment Card via Stripe'
    'Offline Payment'

Campaigns:

    'Events.HUF'
    'singing-for-syrians-2018-guest'
    'syrian-supper-club-guest'

Acknowledgements:

    'singing-for-syrians-2018-thanks'
    'syrian-supper-club-thanks'

Consent Statements:

    'Events.HUF website'

Reasons:

    'Updated in Events.HUF booking'

**Comment by samuelcolvin** [comment]
obviously `singing-for-syrians-2018` now becomes `singing-for-syrians`

**Comment by azadiproductle** [comment]
@samuelcolvin that is correct. I will set-up

**Comment by samuelcolvin** [comment]
great, closing here, but it'll remain if we need to reference it.

**Comment by azadiproductle** [comment]
no, keep open as is a task for me.

**Comment by roselukas** [comment]
Samuel, understand that it might take a bit to change the Departments, as soon as you have please let us know and we'll do final test before going live.

**Comment by samuelcolvin** [comment]
as in #185?

**Comment by samuelcolvin** [comment]
departments and account codes changes, and on scolvin.com for testing. Let me know if there are any problems.

**Comment by roselukas** [comment]
Wonderful we’ll test and let you know.
