### ISSUE TITLE
Receipt from Stripe and Hands Up ticket buyer email

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#166]
The Stripe receipt has the right amount paid, because it includes ticket fee. 

Hands Up's email to ticket buyers only includes the price, without feee, I think this needs to be the same as Stripe version. Trouble is the fee will vary depending on which card they use. So maybe we remove the "total amount charged" in the Ticket buyer email and just have ticket price and tickets purchased. Unless you can think a way around the fee issue? 

![image-1](https://user-images.githubusercontent.com/41365539/47134991-52838800-d2b7-11e8-8636-a419d5630699.jpg)
![image-2](https://user-images.githubusercontent.com/41365539/47134992-52838800-d2b7-11e8-9207-8ce1f924a91e.jpg)

**Comment by samuelcolvin** [comment]
1. I don't think you should send a receipt from stripe. How come they're sending.
2. I'm amazed the fee I is being added on top of the original amount. Pretty sure this is illegal and will pass people off a lot. Let's change it.
