### ISSUE TITLE
Error: No reCAPTCHA clients exist.

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/nosht#173]
https://sentry.io/the-hands-up-foundation/hands-up-events/issues/765830374/?referrer=github_plugin

```
Error: No reCAPTCHA clients exist.
  at Ez (/recaptcha/api2/v1542004393985/recaptcha__en.js:502:486)
  at None (/recaptcha/api2/v1542004393985/recaptcha__en.js:512:96)
  at call (events/BookingLogin.js:80:25)
  at i (events/Book.js:155:25)
  at c (events/Book.js:155:25)
...
(3 additional frame(s) were not displayed)
```

**Comment by samuelcolvin** [comment]
happens on mac and ios mostly.

**Comment by satyendera** [comment]
is it fixed ?

**Comment by samuelcolvin** [comment]
Yes, I believe so. See the commit above.

**Comment by satyendera** [comment]
$('#betaForm').on('submit', function (e) {
                var frm = this;
                e.preventDefault();
                //var widgetId = grecaptcha.render(container);
               
               grecaptcha.execute('6LeDPqgUAAAAAP9YPKn4aITheCkcyjt1YU3zmXke', { action: 'beta' }).then(function (token) {
                  $('[name="g-recaptcha-response"]').val(token);
                  console.log(token);
                  frm.submit();
                }, function (reason) {
                  console.log(reason);
                });
               grecaptcha.reset();
            });

but i still getting this issue

**Comment by satyendera** [comment]
please help me out , how could i fix it

**Comment by samuelcolvin** [comment]
Hi, please can you give some more context:
* where are you running the app, are you running the full nosht system?
* what are you trying to do?
* what device are you using?

Also please format your code [properly](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) so I can read it.

**Comment by satyendera** [comment]
ohk sure .
i m not running nosht system 
it's my jquery based custom application
i want to integrate google reCaptcha v3 earlier it was V2
all things done , token generated but in mac only i am getting this error
Uncaught Error: No reCAPTCHA clients exist.
    at pU (VM16848 recaptcha__en.js:511)
    at Object.Pl [as getResponse] (VM16848 recaptcha__en.js:509)
    at HTMLButtonElement.formSubmitValidation (VM16847 analytics.js:467)
    at HTMLFormElement.dispatch (VM16827 jquery.min.js:5)
    at HTMLFormElement.y.handle (VM16827 jquery.min.js:5)

my code for form submit is 👎 
 $('#betaForm').on('submit', function (e) {
                var frm = this;
                e.preventDefault();
               grecaptcha.execute('6LeDPqgUAAAAAP9YPKn4aITheCkcyjt1YU3zmXke', { action: 'beta' }).then(function (token) {
                  $('[name="g-recaptcha-response"]').val(token);
                  console.log(token);
                  frm.submit();
                }, function (reason) {
                  console.log(reason);
                });
              
            });

**Comment by samuelcolvin** [comment]
okay, this is nothing to do with nosht, please seek help elsewhere, eg. stackoverflow.

also, if you want help in future, take the time to format your code so it can be read easily by others.
