### ISSUE TITLE
Create specific campaigns

### ISSUE THREAD

**Issue by azadiproductle** [samuelcolvin/nosht#174]
<DRAFT>
Donorfy documentation on campaigns [here](https://donorfy.zendesk.com/hc/en-us/articles/360012355733).

When an event is created in Nosht, we should create a Campaign in Donorfy unless (minute chance) it alread exists. 

Campaign name is constructed as
[Category]:[Event Stub]

1) Check for the Campaign. 
`https://data.donorfy.com/api/v1/<apikey>/System/LookUpTypes/Campaigns`
to retrieve all Campaigns

2) Insert new Campaign
`https://data.donorfy.com/api/v1/<apikey>/System/LookUpTypes/Campaigns  `
passing the new campaign in the message body
`{ "LookUpDescription": "[Category]:[Event Stub]" }`
There is no ability to add further details, so there will need to be a process for HUF users to monitor these and add extra detail if needed.

**Comment by samuelcolvin** [comment]
Hi, @azadiproductle you didn't include the link to the documentation. Please could you provide it.

**Comment by samuelcolvin** [comment]
Docs such as they exist: https://donorfy.zendesk.com/hc/en-us/articles/360012355733
