### ISSUE TITLE
Title for Gift Aid declaration not captured

### ISSUE THREAD

**Issue by azadiproductle** [samuelcolvin/nosht#180]
Booked event as guest. 
https://app.donorfy.com/Constituent/Index?Id=e202ccbb-383e-6f05-b282-ff00004460b4&EntityType=Constituent 

Added follow-up Gift, added Gift Aid in the basket process. Added Title of Mr. However, title still blank in the CRM record. 
<img width="747" alt="screenshot 2018-12-10 at 22 35 46" src="https://user-images.githubusercontent.com/41363663/49766046-01e34680-fccc-11e8-881b-c8291076589b.png">

**Comment by samuelcolvin** [comment]
So is the problem just that the "title" field is missing?

Nosht doesn't have a title field. In my experience, they add very little. Is there any reason why we would need it?

**Comment by samuelcolvin** [comment]
Oh, sorry I forgot about it in gift aid. Will look into it.

**Comment by samuelcolvin** [comment]
Afraid this is a fault with donorfy, I just tried this myself.

From the database, here's the giftaid information I entered:

```
+------+-------------------+----------+------------+--------------+-------------+----------------+--------------+------------+----------+---------+
| id   | donation_option   | amount   | gift_aid   | first_name   | last_name   | address        | city         | postcode   | action   | title   |
|------+-------------------+----------+------------+--------------+-------------+----------------+--------------+------------+----------+---------|
| 9    | 1                 | 123.00   | True       | testing      | mytitle     | mytitleaddress | mytitle_city | T1TLE      | 287      | Mr      |
+------+-------------------+----------+------------+--------------+-------------+----------------+--------------+------------+----------+---------+
```

I used different values to distinguish it from the name etc. entered when creating the constituent.

And here's how that data came out in donorfy:

![image](https://user-images.githubusercontent.com/4039449/49796275-24a94580-fd34-11e8-8fd3-1e37b289197f.png)

In other words, donorfy appearent ignores the data entered when creating a transaction.

Here's the section of code responsible for sending the transaction data to donorfy, essentually it just fetches the required data from the database and POSTs it to the `/transactions` endpoint on donorfy:

https://github.com/samuelcolvin/nosht/blob/c470efdae23294c310f0564033f8c9e5d14df489/py/shared/donorfy.py#L294-L338

Again, this looks to me like a problem with donorfy :-)

**Comment by azadiproductle** [comment]
@samuelcolvin Tested and working. Thanks
