### ISSUE TITLE
Question re #179 fix

### ISSUE THREAD

**Issue by azadiproductle** [samuelcolvin/nosht#184]
Hi
To check, have you now taken data out of these 'code' fields and put them into the 'Notes' field? 
URL: /supper-clubs/testhostdec10th-event-3/
location: None
ticket limit: 20
price: £30.00
description: 123456789012345678901234567890123456890123456FIVE. 12345678 trdyuiop'[\;l 
 d;lfkdsa';kfd9012345678901234567890123456890123456FIVE. 123456789012345678901234567890123456890123456FIVE.
<img width="731" alt="screenshot 2018-12-18 at 09 15 22" src="https://user-images.githubusercontent.com/41363663/50143823-840fd400-02a5-11e9-95a2-09667b809c20.png">

**Comment by samuelcolvin** [comment]
answered on #183.

Best to ask follow up questions on the original issue or in the pull request. (Sorry to be such a github pedant).
