### ISSUE TITLE
Change request  - department and bank account

### ISSUE THREAD

**Issue by azadiproductle** [samuelcolvin/nosht#185]
HUF have changed their income code structure. 

Department. 
![image](https://user-images.githubusercontent.com/41363663/50167415-0964aa00-02e1-11e9-8192-371b281e9abc.png)

Instead of it always being 200 Fund Raising Income, we need to use
220 Ticket Sales for all Nosht guest purchases
210 Donations Income for all follow-up donations

Bank Accounts:
Unrestricted Account used rather than Main Account. 

I have added these to Sandbox

**Comment by samuelcolvin** [comment]
Done and on the test server now.
