### ISSUE TITLE
Double transaction records in Donorfy 

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#188]
At the moment double records appear for each transaction that’s pushed through, so you get “connected transaction” and “transaction beneficiary”. This is clearly something for Donorfy to fix, but I think they’ll need some coding info from you. I’m happy to pass that on if you let me know what it is. See screenshot 1
<img width="789" alt="screenshot 1" src="https://user-images.githubusercontent.com/41365539/50172009-f0adc180-02eb-11e9-96e6-9a042efa054c.png">

**Comment by samuelcolvin** [comment]
Currently when we create a transaction we set both `ConnectedConstituentId` and `ExistingConstituentId` to the constitudent id, I didn't because I wasn't sure which one to use. Perhaps if we remove `ConnectedConstituentId` it would resolve it?

**Comment by samuelcolvin** [comment]
Fixed, and merged. I've also rebased #186 after this and deployed so what's in scolvin.com will include both sets of fixes.

**Comment by samuelcolvin** [comment]
turns out I was being an idiot and only removed `ConnectedConsituentId` once and left it in the other place. Fixed in #191.

**Comment by samuelcolvin** [comment]
ok, that's deployed on the testing system.
