### ISSUE TITLE
Tickets already sold while Donorfy's API wasn't in place

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#189]
For tickets we have already sold on the platform (which has all generally gone brilliantly by the way), will these be pushed through when we press go live? We assumed not, so have actually added these manually to Donorfy already. BUT if they will go through when we press go live, let’s stick with that and then we’ll just delete duplicates. Unless there’s a clever way around you can think of? We’re trying to avoid lots of extra work, but the most important thing is that we have the correct info in Donorfy and that it is aligned with the data that will come through in future from Nosht.

**Comment by samuelcolvin** [comment]
Without more work, they won't go through.
