### ISSUE TITLE
Clone events

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/nosht#198]
Button on an event to "Clone event" for admins.

Creates a duplicate event with everything unchanged, admin can then go and change things.

3 hours

**Comment by samuelcolvin** [comment]
* on an event you click "clone"
* you get a modal form asking you to choose when you want the new event to happen and what it's new title should be
* You click "create" and the new event is created, you can then edit the new event if you want to change more things

**Comment by roselukas** [comment]
YES PLEASE
