### ISSUE TITLE
Waiting list

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#225]
![Screenshot 2019-08-20 at 14 27 57](https://user-images.githubusercontent.com/41365539/63351213-bdc63c80-c356-11e9-976d-4ddcefc346e4.png)
For the future, but would be great to have a way of events that are "sold out" appearing as such on the main event page, see screenshot 1. 

Also, it would be amazing to have some kind of waitlist function that guests could sign up to, if something has sold out. We're checking online to see whether there is some free software/page we can use for this in the mean time.

**Comment by samuelcolvin** [comment]
showing "sold out" on the list view should be easy.

Waiting list is much more work but possible.

**Comment by roselukas** [comment]
Hi Samuel

Good to know! Would love to implement the sold out when you have time, let’s leave waiting list as nice to have for now.

Amira is going to come back to you on the other enable/disable issue. I’m off on holiday from this evening and won’t get to it alas.

Thanks so much.

Rose

**Comment by samuelcolvin** [comment]
How would the waiting list work?

I envisage:
* if sold out, you get a box to enter your name and email address, adds you to a waiting list
* When the number of tickets available changes, or tickets are marked as cancelled:
  * everyone on the waiting list get's an email saying "new tickets available"
  * email has a link to buy tickets, but also a button to stop getting more such emails for that event, which removes them from the waiting list

6 hours.

**Comment by roselukas** [comment]
Samuel, 

This sounds like an excellent process for waiting list - YES PLEASE.
