### ISSUE TITLE
FOR NATHAN: Embed video in Event/Fundraiser description

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#265]
Nosht, the platform, was originally built for both Hands Up and hosts to ticket events through. 

Given COVID and general developments, the next stage is for hosts/Hands Up to add a Fundraiser (not necessarily a ticketed event, which may only ask for donations online). Samuel has already added this functionality. 

We would like the ability to embed videos and images on the event/fundraiser landing page. A current fundraiser, organised outside by an external host, involves a Youtube video of a piece of music. The idea is that people watch, enjoy and feel inspired to donate. It would be ideal if we could have this video embedded on the fundraising page. At the moment potential supporters have to click a link which takes them to youtube to watch. Landing page is here: https://events.handsupfoundation.org/singing-for-syrians/syrian-sands-lockdown-edition-VZZN/ 

See Screenshot. 
![Screenshot (19)](https://user-images.githubusercontent.com/41365539/90787263-73c2be80-e2fc-11ea-9d9c-fbfc2dc29dd4.png)

Nathan, please let me know if this is unclear. This would be great to start with, and then going from there, we'll include the other things we're thinking of. Most to do with display over functionality.

**Comment by pro-Nate** [comment]
I have added an optional field to the dashboard which will display an embedded video when filled with a Youtube video id. 
The Syrian sands Lockdown edition has been updated to use this.

**Comment by roselukas** [comment]
The video doesn't seem to work when embedded. 
![image](https://user-images.githubusercontent.com/41365539/94682665-2f740680-031d-11eb-9956-5599ea21fc52.png)

**Comment by pro-Nate** [comment]
> The video doesn't seem to work when embedded.
> ![image](https://user-images.githubusercontent.com/41365539/94682665-2f740680-031d-11eb-9956-5599ea21fc52.png)

It appears to functioning here: https://events.handsupfoundation.org/singing-for-syrians/syrian-sands-lockdown-edition-VZZN/
What's the ID of the video you are trying to embed?

**Comment by roselukas** [comment]
[3:37 PM] Amira Kaadan
    

The only thing that you might need to remember is that the dashboard takes the ID of the video - not the url which can be different depending on where you are or your device ect.

The ID is the bit of code at the end of an embed link usually: 

    https://www.youtube.com/embed/oD9zn9M9NBg

YouTubewww.youtube.com
