### ISSUE TITLE
For Nathan: Fix Facebook login on the event platform

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#269]
When someone wants to book a ticket, they need to sign up on the event platform. There are currently three options but the FB is not working. Can you please fix?
![image](https://user-images.githubusercontent.com/41365539/93492159-69e3a980-f902-11ea-9823-55345af1ba63.png)
![image](https://user-images.githubusercontent.com/41365539/93492193-749e3e80-f902-11ea-9999-383a390f47a6.png)

**Comment by samuelcolvin** [comment]
I think we discussed this. The reason is broken is that we don't let Facebook record all the data they want to record.

We decided just to remove Facebook as a login option.
