### ISSUE TITLE
For Nathan: logo on Events platform not showing

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#270]
Here is a screenshot: 
![image](https://user-images.githubusercontent.com/41365539/93492324-94356700-f902-11ea-9d28-fd88369056d3.png)

**Comment by roselukas** [comment]
Logo 
![Blank background ORANGE](https://user-images.githubusercontent.com/41365539/93492427-b5965300-f902-11ea-8e23-08adac960b91.png)

**Comment by samuelcolvin** [comment]
Fixing this should be as simple as adding `logo.png` to the `deploy-settings-events-handsup/` directory.

**Comment by samuelcolvin** [comment]
correction, to `deploy-settings-events-handsup/favicons/`, slightly weird setup, but that should work.

**Comment by pro-Nate** [comment]
It actually needed to be copied to `js/public/` manually before deploying.
All good now.

**Comment by samuelcolvin** [comment]
For future me coming back to this problem:

> correction, to `deploy-settings-events-handsup/favicons/`, slightly weird setup, but that should work.

This works fine, you just need to make sure docker doesn't cache the following stage:

https://github.com/samuelcolvin/nosht/blob/2804f1b919058e006f82df984991b1b2ef7c74d4/docker/Dockerfile.web#L18
