### ISSUE TITLE
Send different types of email updates to different types of ticket holders

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#283]
Add options for sending different emails to different types of ticket holders. To increase character limit and Rich Text. For both Admin and Host users.
![10](https://user-images.githubusercontent.com/41365539/93999056-4353c180-fd8d-11ea-9691-50f41a19a19c.png)

**Comment by roselukas** [comment]
Does this option apply to donors too (people who donate)?

**Comment by pro-Nate** [comment]
The update system only send to ticket holders. 
There's an open issue for adding donation updates -> #310

**Comment by roselukas** [comment]
I've tested several times but no update email was received. Can you please recheck?

**Comment by pro-Nate** [comment]
This was due to to the email template being marked as "inactive" in the dashboard.
