### ISSUE TITLE
Change Text on Login Screen

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#304]
Change the wording on Login screen for guests when booking tickets to be:
**Login to book your tickets or donate, if you don't have an account then sign up here**

![Screenshot (53)](https://user-images.githubusercontent.com/41365539/95439158-269fb800-094f-11eb-94da-6aad1eeb2e6a.png)

Change the buttons to be Login/Sign up

**Comment by pro-Nate** [comment]
I've updated the message for the category in the image.
The content of this message is populated from a field on the edit category page: 
  `dashboard->categories->thecategory->edit->Booking Trust Message`

Changing the buttons will involve some relatively minor code changes.
