### ISSUE TITLE
Ticket ID to be included in Donorfy Acknowledgement email

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#308]
For now the ticket ID is showing in the 'Acknowledgement Text' field. We want it to be able to show the 'Ticket ID' in another place in the email. 

To be discussed

**Comment by pro-Nate** [comment]
AcknowledgementText seems like the best place to put the ID. 
The Donorfy transaction api offers specific fields in which to pass data but does not appear to allow custom placeholders.
We could try adding one but I doubt it would work.

**Comment by roselukas** [comment]
Ok let's keep the current solution for now.
