### ISSUE TITLE
First name vs email address - Ticket buyer template email

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#31]
Change the text to be "dear firstname" in ticket buyer confirmation email. Currently comes through with "dear email address"

**Comment by samuelcolvin** [comment]
@roselukas what should we put if the user didn't enter a first or last name?

**Comment by roselukas** [comment]
“dear halfwit”

Dear “guest” “ticket buyer” “attendee” my preference is “guest”.

What do you think?

**Comment by samuelcolvin** [comment]
sounds good.

**Comment by samuelcolvin** [comment]
done. In the end name I set name to blank if neither first name nor last name exist since it had to work for all cases including where the recipient wasn't a guest.

**Comment by roselukas** [comment]
Brill!
