### ISSUE TITLE
Add field to external donation link

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#317]

**Comment by pro-Nate** [comment]
Should using this optional field also disable the donation button?

**Comment by roselukas** [comment]
Yes please

**Comment by roselukas** [comment]
HI Nathan, can you update me about this please?

**Comment by pro-Nate** [comment]
> HI Nathan, can you update me about this please?

Done

**Comment by roselukas** [comment]
Thanks all good and working fine.
