### ISSUE TITLE
Scrolling times when setting up event

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#33]
Just practising setting up an event on Nosht. In the date and time section, I can add the date no problem. But I can't scroll down through the list of start times to get past 6pm... Can we fix?

**Comment by samuelcolvin** [comment]
Humm, weird. I can scroll.

I didn't build the component that does the date picker so it's not that trivial to change.

Any other clue on why you can't scroll, would be helpful.

In the meantime, you can just edit the value in the textbox.

**Comment by roselukas** [comment]
Hmmm, yes I can edit easily in the text box so that’s fine.,

Maybe it is just m mac.

We’re doing some testing, and I’ll get a list together of any queries we have and things we feel we’ll want to be able to do and see whether they’re already in your list, not on your list and possible, or impossible.

Rx

**Comment by samuelcolvin** [comment]
closing but let's reopen if it persists.
