### ISSUE TITLE
Explanation text for hosts setting up events

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#69]
I think we need to make it very clear what each text box is for when hosts are filling out their event form, otherwise we'll get a million questions. 

I remember discussing populating with suggested text, but thought this was more of a hindrance. What do you suggest, ideally we'd have greyed out text in each box that disappears when they start to type. But that sounds horribly complicated. 

If we can do this somehow, can I send through what text we want in each box for event set up?

**Comment by roselukas** [comment]
God I'm being slow. Please can we update the text in the "host your own SSC" "Long Description" from: "Full description of the event with everything your guests might like to know" to:

"Tell your guests what they'll need to know, e.g. 
Why you're holding a Syrian Supper Club event
Format of the evening - standing, sitting 
Whether it is bring your own bottle or drink is included in the price
Whether guests will be seated, or can choose where they sit
The menu (if you have it)

**Comment by roselukas** [comment]
I've been through the create an event sequence again, and have a few amendments in the attached. just a couple of text ones. The changes are in red. Hope it makes sense, shout if not. 

[Create event - updates.docx](https://github.com/samuelcolvin/nosht/files/2314457/Create.event.-.updates.docx)

**Comment by samuelcolvin** [comment]
placeholder text is very easy (that's "greyed out text in each box that disappears when they start to type").

Let's discuss tomorrow.

**Comment by samuelcolvin** [comment]
There's also the recommendation text which changes when you set a category. Have you played with that?

**Comment by samuelcolvin** [comment]
Done except for the help text/placeholder on the long description which would be much better done using "host advice" which now scrolls with you in a sexy way as you move down the page.
