### ISSUE TITLE
Can we have a "remember me" box when we login...

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#72]
... so details and password are retained?

Also login with Gmail and Facebook currently now working.

**Comment by samuelcolvin** [comment]
I don't really know what "remember me" means, it's always been a slight anathema to me.

We could extend the duration of cookies. Currently your session will expire if you don't go to a page requiring authentication for 25 hours, but we could easily extend that.

Gmail login is working fine for me. What problem did you have? You could add a logo to make their sign in form smarter, but that's not stopping it working.

Facebook requires you to finish setup of the "app" in facebook's developer dashboard.

**Comment by roselukas** [comment]
I suppose I always think it will remember my username at least… which is helpful.

Might be worth extending therefore…

Made the Gmail etc… work. I’ll look into Facebook app thing.

Danke!

R
