### ISSUE TITLE
Correction to ticket confirmation email text... SfS events...

### ISSUE THREAD

**Issue by roselukas** [samuelcolvin/nosht#74]
<img width="619" alt="screen shot 2018-08-23 at 13 13 32" src="https://user-images.githubusercontent.com/41365539/44524714-7e7af680-a6d6-11e8-9df7-ecec89597107.png">

remove "not provided" from the sentence: 

"Do you have extra requirements? Tell us here not provided, please let the event host Marina Carnwath know if you have any special requirements.

**Comment by samuelcolvin** [comment]
This is be because the template reads

```
{{ ticket_extra_title }} not provided, please let the event host
```

If `ticket_extra_title` was "Dietary requirements" this sentence would read 

```
Dietary requirements not provided, please let the event host
```

Easiest for you to just edit the email definition as you wish.

**Comment by roselukas** [comment]
Ok, easy – I can do this.
