### ISSUE TITLE
API: tag hosts

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/nosht#95]
`constituents/{id}/AddActiveTags` with either `<category slug>-host`.

API endpoint for donorfy is currently broken and returning 500.

**Comment by azadiproductle** [comment]
@roselukas This is a better definition of host than orig suggested. However, you/ Marina need to create the following tags in Sandbox: 
Tag Category: “Hosting and helper volunteers”
Tags:  "[NOSHT EVENT CATEGORY]-Host"
You will need to edit existing tags to match "SSC Host” and “SfS Event Holder”

@samuelcolvin  the tag should be <Hosting and helper volunteers_<NOSHT EVENT CATEGORY>-Host> Note capitalisation. Also note that underscore character separates the tag category from the tag. See email I forwarded from Ben Brett for help on getting this bit of the API working.

**Comment by roselukas** [comment]
Hi Azadi

Thanks for this – Marina, Amira FYI.

Marina – please can you work with Azadi to update the Tag Category with the relevant tags for hosts coming in via the events platform?

Thank you!

R

**Comment by azadiproductle** [comment]
@samuelcolvin I added the correct tags into SANDBOX based on the categories in there: 
supper-club-host
singing-events-host

I notice that only "host" was added as a tag. Please adjust code to take account of these corrected tags.

**Comment by azadiproductle** [comment]
Marina/ Amira – I added these tags in on Monday night. No action.

direct: +44 20 3286 6595 | mobile: +44 7837 566 595 | mail: azadi@productle.com<mailto:azadi@productle.com>
Productle Ltd, 3rd Floor, Buckingham House, Buckingham Street Aylesbury, HP20 2LA
