### ISSUE TITLE
API: guest makes donation

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/nosht#98]
create an activity, a transaction and an allocation when someone donates.

`POST /api/v1/{apiKey}/activities`
```json
{
  "ExistingConstituentId": "guest's ID",
  "ActivityType": "Event Booked",
  "ActivityDate": "[Date of booking]", 
  "Campaign": "[Category]",
  "Notes": "extra information/dietary reqs.",
  "Code1": "id of the buying individual",
  "Number1": "price",
  "Number1": "number of tickets",
  "YesNo1": "wethery they booked it themselves",
  "Date1": "[date of event]"
}
```

`POST /api/v1/{apiKey}/transactions`
```json
{
  "ConnectedConstituentId": "buyer's id",
  "Channel": "[Event Category, donation option?]",
  "Currency": "currency",
  "Campaign": "[Event Category]",
  "PaymentMethod": "Payment Card via Stripe",
  "Department": "200 Fund Raising Income",
  "BankAccount": "Unrestricted Account",
  "DatePaid": "Date-Time of Transaction",
  "Amount": "total including 'cover costs'",
  "Acknowledgement": "[Category] plus Ticket Thanks",
  "AcknowledgementText": "string",
  "Reference": "nosht:category/event-slug.donation-option-id",
  "ProcessingCostsAmount": "stripe fee"
}
```

`POST /api/v1/{apiKey}/transactions/{id}/AddAllocation`
```json
{
  "AllocationId": "presumably this shouldn't be here as we're creating an allocation",
  "Product": "[event name][donation option]: coving costs",
  "Quantity": 1,
  "Amount": "amount",
  "Department": "200 Fund Raising Income",
  "Fund": " Unrestricted General ",
  "AllocationDate": "Date-Time of Transaction",
  "CanRecoverTax": true,
  "Comments": "ticket-purchase",
  "BeneficiaryConstituentDescription": "string",
  "BeneficiaryConstituentId": "buyer's user id?"
}
```

**Comment by samuelcolvin** [comment]
do we need activity as well as a transaction?

**Comment by azadiproductle** [comment]
@samuelcolvin we do not need the activity. 
We do need a Gift Aid Transaction when the Gift Aid checkbox is checked. 
POST /api/v1/{apiKey}/constituents/{id}/GiftAidDeclarations
{
  "DeclarationMethod": "Online",
  "ConstituentId": "00000000-0000-0000-0000-000000000000",
  "Campaign": "[Category]",
  "DeclarationDate": "2018-08-28T18:07:54.501Z", Date Given (same as Transaction)
  "DeclarationStartDate": "2018-08-28T18:07:54.501Z", Date Given minus four years
  "DeclarationEndDate": "2018-08-28T18:07:54.501Z", Date Given plus 99 years
  "TaxPayerTitle": "MrMs",
  "TaxPayerFirstName": "[First Name]",
  "TaxPayerLastName": "[ Last Name]",
  "ConfirmationRequired": false
}

Other edits: 
POST /api/v1/{apiKey}/transactions
 "Channel": "[Event Category]"
"Currency": "GBP",
  "AcknowledgementText": "donation-option-id",
  "Reference": "Events.HUF:<category> <event-slug>",    (note use of spaces)

One transaction is added to cover the total transaction, with an allocation each for the event and the cover costs elements. The cover costs element is not required if the guest does not agree to cover costs. 

Ticket element Allocation: 
  "Product": "Event Ticket(s)" 
  "Quantity": 0, Number of tickets
  "Amount": 0, Amount total for tickets
  "Department": "200 Fund Raising Income",
  "Fund": " Unrestricted General ",
  "AllocationDate": "2018-08-28T18:07:54.691Z" Date-Time of Transaction,
  "CanRecoverTax": false,
  "Comments": "[Category] [Event Name]" - am assuming 'Event Name' is same as slug. If not, lmk difference and I will confirm which best in this and elsewhere used.  

 Donation element Allocation (also used for follow-up donations): 
  "Product": "Donation" 
  "Quantity": 1
  "Amount": 0, Amount total for donations
  "Department": "200 Fund Raising Income",
  "Fund": " Unrestricted General ",
  "AllocationDate": "2018-08-28T18:07:54.691Z" Date-Time of Transaction,
  "CanRecoverTax": true,
  "Comments": "[Category] [Event Name]" - am assuming 'Event Name' is same as slug. If not, lmk difference and I will confirm which best in this and elsewhere used.

**Comment by samuelcolvin** [comment]
I'm slightly confused, looks like some of this should be on #97? Eg. this is just about extra donations on the donations page. #97 is about the actual buying of tickets for events.

**Comment by azadiproductle** [comment]
I can see why. When an individual buys a ticket, the main portion is a ticket. The 3% is a donation. If they they make a follow-up donation, then it is a 100% donation. Donorfy handles this as follows:
Main purchase (Issue 97): one transaction + two allocations (one for ticket and one for donation)
Donation (Issue 98): one transaction + one allocation
The data for the donation allocation is the same in both 97 and 98.

**Comment by azadiproductle** [comment]
Also - Transaction needs something different in 98 than 97:
 "Acknowledgement": "[Category] plus Donation Thanks",
  "AcknowledgementText": "some URN from Stripe or NOSHT",
